name: Go

on:
  push:
    branches: [ run_my_way, feature ]
  pull_request:
    branches: [ run_my_way, feature ]
  schedule:
  # 早上8点和晚上9点33分进行打卡
    - cron: '33 0,13 * * *' 


jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: go build

    - name: Run
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        FT_SCKEY: ${{ secrets.FT_SCKEY }}
      run: ./autosubmit
